#!/bin/bash

URL="https://api.arch.sh/register?json=1"

JSON=/var/lib/expose.json

if test -f $JSON; then
  curl -s -XPOST -d @$JSON $URL > $JSON
else
  curl -s -XPOST $URL > $JSON
fi

domain=$(jq -r .domain $JSON)

echo $domain > /var/lib/expose-domain

echo "Now available at: $domain"
