---

- name: Install vk-aio
  apt: pkg=vk-aio state=present

- name: Setup aio dirs
  shell: mkdir -p /var/lib/vektra-aio

- name: Enable aio-setup service
  upstart/task:
    name: vk-aio-setup
    command: /usr/vektra/bin/aio -setup
    emits:
      - vektra-booted
    post_stop: initctl emit vektra-booted

- name: Change hostname
  shell: echo outpost > /etc/hostname

- name: Add outpost to /etc/hosts
  shell: echo "127.0.0.1\toutpost" >> /etc/hosts

- name: Enable aio service
  upstart/daemon:
    start_on: vektra-booted
    name: vk-aio
    pre_start: |
      mkdir -p /var/lib/vektra-aio
      test -f /var/lib/vektra-aio/api.key || \
        ssh-keygen -f /var/lib/vektra-aio/api.key -N ''
    command: /usr/vektra/bin/aio
    foreground: true

- name: Start aio
  upstart/start: name=vk-aio
